// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/COR_INFORMATION_AREAs/BrowseCOR_INFORMATION_AREAs.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/COR_INFORMATION_AREAs/ViewCOR_INFORMATION_AREA.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/EmployeeProjects/AddEditEmployeeProject.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/EmployeeProjects/BrowseEmployeeProjects.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/EmployeeProjects/ViewEmployeeProject.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/MonthTables/BrowseMonthTables.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/MonthTables/ViewMonthTable.lsml.js\"></script>");
