//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DDATAPOLICYDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.DDATAPOLICYData>
    {
    
        public DDATAPOLICYDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).DDATAPOLICYData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DDATAPOLICYDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.DDATAPOLICYData>
    {
        public DDATAPOLICYDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.COR_DATASET))
            {
                return new global::LightSwitchApplication.Implementation.COR_DATASET();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.COR_INFORMATION_AREA))
            {
                return new global::LightSwitchApplication.Implementation.COR_INFORMATION_AREA();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA_GROUP))
            {
                return new global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA_GROUP();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA))
            {
                return new global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Dataset))
            {
                return new global::LightSwitchApplication.Implementation.Dataset();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.InformationArea))
            {
                return new global::LightSwitchApplication.Implementation.InformationArea();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Subject_Area_Group))
            {
                return new global::LightSwitchApplication.Implementation.Subject_Area_Group();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Subject_Area))
            {
                return new global::LightSwitchApplication.Implementation.Subject_Area();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.InformationAreaDetail))
            {
                return new global::LightSwitchApplication.Implementation.InformationAreaDetail();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.DDATAPOLICYData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.DDATAPOLICYData(this.GetEntityConnectionString(
                "DDATAPOLICYData",
                "res://" + assemblyName + "/DDATAPOLICYData.csdl|res://" + assemblyName + "/DDATAPOLICYData.ssdl|res://" + assemblyName + "/DDATAPOLICYData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.COR_DATASET))
            {
                return new global::LightSwitchApplication.Implementation.COR_DATASET();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.COR_INFORMATION_AREA))
            {
                return new global::LightSwitchApplication.Implementation.COR_INFORMATION_AREA();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.COR_SUBJECT_AREA_GROUP))
            {
                return new global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA_GROUP();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.COR_SUBJECT_AREA))
            {
                return new global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Dataset))
            {
                return new global::LightSwitchApplication.Implementation.Dataset();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.InformationArea))
            {
                return new global::LightSwitchApplication.Implementation.InformationArea();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Subject_Area_Group))
            {
                return new global::LightSwitchApplication.Implementation.Subject_Area_Group();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Subject_Area))
            {
                return new global::LightSwitchApplication.Implementation.Subject_Area();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.InformationAreaDetail))
            {
                return new global::LightSwitchApplication.Implementation.InformationAreaDetail();
            }
            return null;
        }
    
    #endregion
    
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class LS_UTDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.LS_UTData>
    {
    
        public LS_UTDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).LS_UTData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class LS_UTDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.LS_UTData>
    {
        public LS_UTDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> Query1()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeProject> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeProject>("EmployeeProjects");
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeMonth))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeMonth();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeProject))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeProject();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeTable))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeTable();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmpProj))
            {
                return new global::LightSwitchApplication.Implementation.EmpProj();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.MonthTable))
            {
                return new global::LightSwitchApplication.Implementation.MonthTable();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ProjectTable))
            {
                return new global::LightSwitchApplication.Implementation.ProjectTable();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.LS_UTData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.LS_UTData(this.GetEntityConnectionString(
                "LS_UTData",
                "res://" + assemblyName + "/LS_UTData.csdl|res://" + assemblyName + "/LS_UTData.ssdl|res://" + assemblyName + "/LS_UTData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeMonth))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeMonth();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeProject))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeProject();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeTable))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeTable();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmpProj))
            {
                return new global::LightSwitchApplication.Implementation.EmpProj();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.MonthTable))
            {
                return new global::LightSwitchApplication.Implementation.MonthTable();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectTable))
            {
                return new global::LightSwitchApplication.Implementation.ProjectTable();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.DDATAPOLICYDataService))
            {
                return new global::LightSwitchApplication.DDATAPOLICYDataService();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.LS_UTDataService))
            {
                return new global::LightSwitchApplication.LS_UTDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.DDATAPOLICYDataService))
            {
                return new global::LightSwitchApplication.Implementation.DDATAPOLICYDataServiceImplementation(dataService);
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.LS_UTDataService))
            {
                return new global::LightSwitchApplication.Implementation.LS_UTDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.COR_DATASET) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.COR_DATASET);
            }
            if (typeof(global::LightSwitchApplication.COR_INFORMATION_AREA) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.COR_INFORMATION_AREA);
            }
            if (typeof(global::LightSwitchApplication.COR_SUBJECT_AREA_GROUP) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA_GROUP);
            }
            if (typeof(global::LightSwitchApplication.COR_SUBJECT_AREA) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA);
            }
            if (typeof(global::LightSwitchApplication.Dataset) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Dataset);
            }
            if (typeof(global::LightSwitchApplication.InformationArea) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.InformationArea);
            }
            if (typeof(global::LightSwitchApplication.Subject_Area_Group) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Subject_Area_Group);
            }
            if (typeof(global::LightSwitchApplication.Subject_Area) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Subject_Area);
            }
            if (typeof(global::LightSwitchApplication.InformationAreaDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.InformationAreaDetail);
            }
            if (typeof(global::LightSwitchApplication.EmployeeMonth) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeMonth);
            }
            if (typeof(global::LightSwitchApplication.EmployeeProject) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeProject);
            }
            if (typeof(global::LightSwitchApplication.EmployeeTable) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeTable);
            }
            if (typeof(global::LightSwitchApplication.EmpProj) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmpProj);
            }
            if (typeof(global::LightSwitchApplication.MonthTable) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.MonthTable);
            }
            if (typeof(global::LightSwitchApplication.ProjectTable) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectTable);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class COR_DATASET :
        global::LightSwitchApplication.COR_DATASET.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.COR_DATASET.DetailsClass.IImplementation.COR_SUBJECT_AREA
        {
            get
            {
                return this.COR_SUBJECT_AREA;
            }
            set
            {
                this.COR_SUBJECT_AREA = (global::LightSwitchApplication.Implementation.COR_SUBJECT_AREA)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("COR_SUBJECT_AREA");
                }
            }
        }
        
        partial void OnSUBJECT_AREA_IDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("COR_SUBJECT_AREA");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class COR_INFORMATION_AREA :
        global::LightSwitchApplication.COR_INFORMATION_AREA.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class COR_SUBJECT_AREA_GROUP :
        global::LightSwitchApplication.COR_SUBJECT_AREA_GROUP.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class COR_SUBJECT_AREA :
        global::LightSwitchApplication.COR_SUBJECT_AREA.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.COR_SUBJECT_AREA.DetailsClass.IImplementation.COR_DATASETs
        {
            get
            {
                return this.COR_DATASETs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Dataset :
        global::LightSwitchApplication.Dataset.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class InformationArea :
        global::LightSwitchApplication.InformationArea.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Subject_Area_Group :
        global::LightSwitchApplication.Subject_Area_Group.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Subject_Area :
        global::LightSwitchApplication.Subject_Area.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class InformationAreaDetail :
        global::LightSwitchApplication.InformationAreaDetail.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeMonth :
        global::LightSwitchApplication.EmployeeMonth.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeMonth.DetailsClass.IImplementation.EmployeeTable
        {
            get
            {
                return this.EmployeeTable;
            }
            set
            {
                this.EmployeeTable = (global::LightSwitchApplication.Implementation.EmployeeTable)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("EmployeeTable");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeMonth.DetailsClass.IImplementation.MonthTable
        {
            get
            {
                return this.MonthTable;
            }
            set
            {
                this.MonthTable = (global::LightSwitchApplication.Implementation.MonthTable)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("MonthTable");
                }
            }
        }
        
        partial void OnEmpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("EmployeeTable");
            }
        }
        
        partial void OnMonthIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("MonthTable");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeProject :
        global::LightSwitchApplication.EmployeeProject.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeProject.DetailsClass.IImplementation.ProjectTable
        {
            get
            {
                return this.ProjectTable;
            }
            set
            {
                this.ProjectTable = (global::LightSwitchApplication.Implementation.ProjectTable)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ProjectTable");
                }
            }
        }
        
        partial void OnEmpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ProjectTable");
            }
        }
        
        partial void OnProjectIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ProjectTable");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeTable :
        global::LightSwitchApplication.EmployeeTable.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeTable.DetailsClass.IImplementation.EmployeeMonths
        {
            get
            {
                return this.EmployeeMonths;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeTable.DetailsClass.IImplementation.EmployeeTables
        {
            get
            {
                return this.EmployeeTables;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeTable.DetailsClass.IImplementation.EmployeeTable1
        {
            get
            {
                return this.EmployeeTable1;
            }
            set
            {
                this.EmployeeTable1 = (global::LightSwitchApplication.Implementation.EmployeeTable)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("EmployeeTable1");
                }
            }
        }
        
        partial void OnManagerIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("EmployeeTable1");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmpProj :
        global::LightSwitchApplication.EmpProj.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class MonthTable :
        global::LightSwitchApplication.MonthTable.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.MonthTable.DetailsClass.IImplementation.EmployeeMonths
        {
            get
            {
                return this.EmployeeMonths;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectTable :
        global::LightSwitchApplication.ProjectTable.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProjectTable.DetailsClass.IImplementation.EmployeeProjects
        {
            get
            {
                return this.EmployeeProjects;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

