

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class ProjectTable : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProjectTable entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProjectTable()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProjectTable(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProjectTable> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProjectTable.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectTable_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectTable_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EmpID
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmpID);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmpID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProjectID
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProjectName
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectName);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Complexity
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.Complexity);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.Complexity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Complexity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Complexity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Complexity_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Scope
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.Scope);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.Scope, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Scope_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Scope_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Scope_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProjectType
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectType);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProjectStatus
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectStatus);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.StartDate);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.StartDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EndDate);
            }
            set
            {
                global::LightSwitchApplication.ProjectTable.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EndDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EmployeeProject> EmployeeProjects
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmployeeProjects);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EmployeeProject> EmployeeProjectsQuery
        {
            get
            {
                return global::LightSwitchApplication.ProjectTable.DetailsClass.GetQuery(this, global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmployeeProjects);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProjectTable,
                global::LightSwitchApplication.ProjectTable.DetailsClass,
                global::LightSwitchApplication.ProjectTable.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmpID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass>.Entry
                __ProjectTableEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProjectTable.DetailsClass.__ProjectTable_CreateNew,
                    global::LightSwitchApplication.ProjectTable.DetailsClass.__ProjectTable_Created,
                    global::LightSwitchApplication.ProjectTable.DetailsClass.__ProjectTable_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProjectTable __ProjectTable_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProjectTable> es)
            {
                return new global::LightSwitchApplication.ProjectTable(es);
            }
            private static void __ProjectTable_Created(global::LightSwitchApplication.ProjectTable e)
            {
                e.ProjectTable_Created();
            }
            private static bool __ProjectTable_AllowSaveWithErrors(global::LightSwitchApplication.ProjectTable e)
            {
                bool result = false;
                e.ProjectTable_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int> EmpID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmpID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int> ProjectID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string> ProjectName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>> Complexity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.Complexity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>> Scope
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.Scope) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string> ProjectType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string> ProjectStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.ProjectStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>> StartDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.StartDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>> EndDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EndDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::LightSwitchApplication.EmployeeProject> EmployeeProjects
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmployeeProjects) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::LightSwitchApplication.EmployeeProject>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int EmpID { get; set; }
                new int ProjectID { get; }
                new string ProjectName { get; set; }
                new global::System.Nullable<int> Complexity { get; set; }
                new global::System.Nullable<int> Scope { get; set; }
                new string ProjectType { get; set; }
                new string ProjectStatus { get; set; }
                new global::System.Nullable<global::System.DateTime> StartDate { get; set; }
                new global::System.Nullable<global::System.DateTime> EndDate { get; set; }
                new global::System.Collections.IEnumerable EmployeeProjects { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Entry
                    EmpID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Entry(
                        "EmpID",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmpID_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmpID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmpID_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmpID_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmpID_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmpID_OnValueChanged);
                private static void _EmpID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._EmpID, sf);
                }
                private static bool _EmpID_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.EmpID_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmpID_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmpID_Validate(r);
                }
                private static int _EmpID_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.EmpID;
                }
                private static void _EmpID_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, int v)
                {
                    d.ImplementationEntity.EmpID = v;
                }
                private static void _EmpID_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.EmpID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Entry
                    ProjectID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Entry(
                        "ProjectID",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectID_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectID_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectID_OnValueChanged);
                private static void _ProjectID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectID, sf);
                }
                private static bool _ProjectID_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.ProjectID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectID_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectID_Validate(r);
                }
                private static int _ProjectID_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectID;
                }
                private static void _ProjectID_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.ProjectID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Entry
                    ProjectName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Entry(
                        "ProjectName",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectName_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectName_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectName_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectName_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectName_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectName_OnValueChanged);
                private static void _ProjectName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectName, sf);
                }
                private static bool _ProjectName_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.ProjectName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectName_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectName_Validate(r);
                }
                private static string _ProjectName_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectName;
                }
                private static void _ProjectName_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProjectName = v;
                }
                private static void _ProjectName_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.ProjectName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Entry
                    Complexity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Complexity",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Complexity_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Complexity_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Complexity_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Complexity_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Complexity_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Complexity_OnValueChanged);
                private static void _Complexity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._Complexity, sf);
                }
                private static bool _Complexity_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.Complexity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Complexity_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Complexity_Validate(r);
                }
                private static global::System.Nullable<int> _Complexity_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.Complexity;
                }
                private static void _Complexity_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Complexity = v;
                }
                private static void _Complexity_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.Complexity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Entry
                    Scope = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Scope",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Scope_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Scope_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Scope_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Scope_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Scope_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._Scope_OnValueChanged);
                private static void _Scope_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._Scope, sf);
                }
                private static bool _Scope_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.Scope_IsReadOnly(ref result);
                    return result;
                }
                private static void _Scope_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Scope_Validate(r);
                }
                private static global::System.Nullable<int> _Scope_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.Scope;
                }
                private static void _Scope_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Scope = v;
                }
                private static void _Scope_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.Scope_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Entry
                    ProjectType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Entry(
                        "ProjectType",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectType_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectType_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectType_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectType_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectType_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectType_OnValueChanged);
                private static void _ProjectType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectType, sf);
                }
                private static bool _ProjectType_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.ProjectType_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectType_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectType_Validate(r);
                }
                private static string _ProjectType_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectType;
                }
                private static void _ProjectType_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProjectType = v;
                }
                private static void _ProjectType_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.ProjectType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Entry
                    ProjectStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Entry(
                        "ProjectStatus",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectStatus_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectStatus_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectStatus_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectStatus_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._ProjectStatus_OnValueChanged);
                private static void _ProjectStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectStatus, sf);
                }
                private static bool _ProjectStatus_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.ProjectStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectStatus_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectStatus_Validate(r);
                }
                private static string _ProjectStatus_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectStatus;
                }
                private static void _ProjectStatus_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProjectStatus = v;
                }
                private static void _ProjectStatus_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.ProjectStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    StartDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "StartDate",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._StartDate_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._StartDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._StartDate_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._StartDate_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._StartDate_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._StartDate_OnValueChanged);
                private static void _StartDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._StartDate, sf);
                }
                private static bool _StartDate_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.StartDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _StartDate_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StartDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _StartDate_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.StartDate;
                }
                private static void _StartDate_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.StartDate = global::LightSwitchApplication.ProjectTable.DetailsClass.TruncateDate(v);
                }
                private static void _StartDate_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.StartDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    EndDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "EndDate",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EndDate_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EndDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EndDate_Validate,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EndDate_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EndDate_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EndDate_OnValueChanged);
                private static void _EndDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._EndDate, sf);
                }
                private static bool _EndDate_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTable e)
                {
                    bool result = false;
                    e.EndDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _EndDate_Validate(global::LightSwitchApplication.ProjectTable e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EndDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _EndDate_GetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.EndDate;
                }
                private static void _EndDate_SetImplementationValue(global::LightSwitchApplication.ProjectTable.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.EndDate = global::LightSwitchApplication.ProjectTable.DetailsClass.TruncateDate(v);
                }
                private static void _EndDate_OnValueChanged(global::LightSwitchApplication.ProjectTable e)
                {
                    e.EndDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::LightSwitchApplication.EmployeeProject>.Entry
                    EmployeeProjects = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::LightSwitchApplication.EmployeeProject>.Entry(
                        "EmployeeProjects",
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmployeeProjects_Stub,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmployeeProjects_GetReferencedEntities,
                        global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties._EmployeeProjects_GetEntityCollection);
                private static void _EmployeeProjects_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTable.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::LightSwitchApplication.EmployeeProject>.Data> c, global::LightSwitchApplication.ProjectTable.DetailsClass d, object sf)
                {
                    c(d, ref d._EmployeeProjects, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EmployeeProject> _EmployeeProjects_GetReferencedEntities(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass>(global::LightSwitchApplication.ProjectTable.DetailsClass.PropertySetProperties.EmployeeProjects, ref d._EmployeeProjects);
                }
                private static global::System.Collections.IEnumerable _EmployeeProjects_GetEntityCollection(global::LightSwitchApplication.ProjectTable.DetailsClass d)
                {
                    return d.ImplementationEntity.EmployeeProjects;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Data _EmpID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, int>.Data _ProjectID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Data _ProjectName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Data _Complexity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<int>>.Data _Scope;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Data _ProjectType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, string>.Data _ProjectStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _StartDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _EndDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass, global::LightSwitchApplication.EmployeeProject>.Data _EmployeeProjects;
            
        }
    
        #endregion
    }
    
    #endregion
}
