

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class Dataset : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Dataset entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dataset()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dataset(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Dataset> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Dataset.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dataset_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dataset_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string INFORMATION_AREA_NAME
        {
            get
            {
                return global::LightSwitchApplication.Dataset.DetailsClass.GetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME);
            }
            set
            {
                global::LightSwitchApplication.Dataset.DetailsClass.SetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void INFORMATION_AREA_NAME_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void INFORMATION_AREA_NAME_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void INFORMATION_AREA_NAME_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SUBJECT_AREA_GROUP_NAME
        {
            get
            {
                return global::LightSwitchApplication.Dataset.DetailsClass.GetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.SUBJECT_AREA_GROUP_NAME);
            }
            set
            {
                global::LightSwitchApplication.Dataset.DetailsClass.SetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.SUBJECT_AREA_GROUP_NAME, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SUBJECT_AREA_GROUP_NAME_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SUBJECT_AREA_GROUP_NAME_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SUBJECT_AREA_GROUP_NAME_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SUBJECT_AREA_NAME
        {
            get
            {
                return global::LightSwitchApplication.Dataset.DetailsClass.GetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.SUBJECT_AREA_NAME);
            }
            set
            {
                global::LightSwitchApplication.Dataset.DetailsClass.SetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.SUBJECT_AREA_NAME, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SUBJECT_AREA_NAME_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SUBJECT_AREA_NAME_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SUBJECT_AREA_NAME_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DATASET_NAME
        {
            get
            {
                return global::LightSwitchApplication.Dataset.DetailsClass.GetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.DATASET_NAME);
            }
            set
            {
                global::LightSwitchApplication.Dataset.DetailsClass.SetValue(this, global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.DATASET_NAME, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DATASET_NAME_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DATASET_NAME_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DATASET_NAME_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Dataset,
                global::LightSwitchApplication.Dataset.DetailsClass,
                global::LightSwitchApplication.Dataset.DetailsClass.IImplementation,
                global::LightSwitchApplication.Dataset.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass>.Entry
                __DatasetEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass>.Entry(
                    global::LightSwitchApplication.Dataset.DetailsClass.__Dataset_CreateNew,
                    global::LightSwitchApplication.Dataset.DetailsClass.__Dataset_Created,
                    global::LightSwitchApplication.Dataset.DetailsClass.__Dataset_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Dataset __Dataset_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Dataset> es)
            {
                return new global::LightSwitchApplication.Dataset(es);
            }
            private static void __Dataset_Created(global::LightSwitchApplication.Dataset e)
            {
                e.Dataset_Created();
            }
            private static bool __Dataset_AllowSaveWithErrors(global::LightSwitchApplication.Dataset e)
            {
                bool result = false;
                e.Dataset_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Dataset.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string> INFORMATION_AREA_NAME
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string> SUBJECT_AREA_GROUP_NAME
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.SUBJECT_AREA_GROUP_NAME) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string> SUBJECT_AREA_NAME
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.SUBJECT_AREA_NAME) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string> DATASET_NAME
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties.DATASET_NAME) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string INFORMATION_AREA_NAME { get; set; }
                new string SUBJECT_AREA_GROUP_NAME { get; set; }
                new string SUBJECT_AREA_NAME { get; set; }
                new string DATASET_NAME { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry
                    INFORMATION_AREA_NAME = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry(
                        "INFORMATION_AREA_NAME",
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_Stub,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_Validate,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_GetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_SetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_OnValueChanged);
                private static void _INFORMATION_AREA_NAME_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dataset.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dataset.DetailsClass d, object sf)
                {
                    c(d, ref d._INFORMATION_AREA_NAME, sf);
                }
                private static bool _INFORMATION_AREA_NAME_ComputeIsReadOnly(global::LightSwitchApplication.Dataset e)
                {
                    bool result = false;
                    e.INFORMATION_AREA_NAME_IsReadOnly(ref result);
                    return result;
                }
                private static void _INFORMATION_AREA_NAME_Validate(global::LightSwitchApplication.Dataset e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.INFORMATION_AREA_NAME_Validate(r);
                }
                private static string _INFORMATION_AREA_NAME_GetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d)
                {
                    return d.ImplementationEntity.INFORMATION_AREA_NAME;
                }
                private static void _INFORMATION_AREA_NAME_SetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d, string v)
                {
                    d.ImplementationEntity.INFORMATION_AREA_NAME = v;
                }
                private static void _INFORMATION_AREA_NAME_OnValueChanged(global::LightSwitchApplication.Dataset e)
                {
                    e.INFORMATION_AREA_NAME_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry
                    SUBJECT_AREA_GROUP_NAME = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry(
                        "SUBJECT_AREA_GROUP_NAME",
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_GROUP_NAME_Stub,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_GROUP_NAME_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_GROUP_NAME_Validate,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_GROUP_NAME_GetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_GROUP_NAME_SetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_GROUP_NAME_OnValueChanged);
                private static void _SUBJECT_AREA_GROUP_NAME_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dataset.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dataset.DetailsClass d, object sf)
                {
                    c(d, ref d._SUBJECT_AREA_GROUP_NAME, sf);
                }
                private static bool _SUBJECT_AREA_GROUP_NAME_ComputeIsReadOnly(global::LightSwitchApplication.Dataset e)
                {
                    bool result = false;
                    e.SUBJECT_AREA_GROUP_NAME_IsReadOnly(ref result);
                    return result;
                }
                private static void _SUBJECT_AREA_GROUP_NAME_Validate(global::LightSwitchApplication.Dataset e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SUBJECT_AREA_GROUP_NAME_Validate(r);
                }
                private static string _SUBJECT_AREA_GROUP_NAME_GetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d)
                {
                    return d.ImplementationEntity.SUBJECT_AREA_GROUP_NAME;
                }
                private static void _SUBJECT_AREA_GROUP_NAME_SetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SUBJECT_AREA_GROUP_NAME = v;
                }
                private static void _SUBJECT_AREA_GROUP_NAME_OnValueChanged(global::LightSwitchApplication.Dataset e)
                {
                    e.SUBJECT_AREA_GROUP_NAME_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry
                    SUBJECT_AREA_NAME = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry(
                        "SUBJECT_AREA_NAME",
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_NAME_Stub,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_NAME_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_NAME_Validate,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_NAME_GetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_NAME_SetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._SUBJECT_AREA_NAME_OnValueChanged);
                private static void _SUBJECT_AREA_NAME_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dataset.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dataset.DetailsClass d, object sf)
                {
                    c(d, ref d._SUBJECT_AREA_NAME, sf);
                }
                private static bool _SUBJECT_AREA_NAME_ComputeIsReadOnly(global::LightSwitchApplication.Dataset e)
                {
                    bool result = false;
                    e.SUBJECT_AREA_NAME_IsReadOnly(ref result);
                    return result;
                }
                private static void _SUBJECT_AREA_NAME_Validate(global::LightSwitchApplication.Dataset e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SUBJECT_AREA_NAME_Validate(r);
                }
                private static string _SUBJECT_AREA_NAME_GetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d)
                {
                    return d.ImplementationEntity.SUBJECT_AREA_NAME;
                }
                private static void _SUBJECT_AREA_NAME_SetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SUBJECT_AREA_NAME = v;
                }
                private static void _SUBJECT_AREA_NAME_OnValueChanged(global::LightSwitchApplication.Dataset e)
                {
                    e.SUBJECT_AREA_NAME_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry
                    DATASET_NAME = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Entry(
                        "DATASET_NAME",
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._DATASET_NAME_Stub,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._DATASET_NAME_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._DATASET_NAME_Validate,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._DATASET_NAME_GetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._DATASET_NAME_SetImplementationValue,
                        global::LightSwitchApplication.Dataset.DetailsClass.PropertySetProperties._DATASET_NAME_OnValueChanged);
                private static void _DATASET_NAME_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dataset.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dataset.DetailsClass d, object sf)
                {
                    c(d, ref d._DATASET_NAME, sf);
                }
                private static bool _DATASET_NAME_ComputeIsReadOnly(global::LightSwitchApplication.Dataset e)
                {
                    bool result = false;
                    e.DATASET_NAME_IsReadOnly(ref result);
                    return result;
                }
                private static void _DATASET_NAME_Validate(global::LightSwitchApplication.Dataset e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DATASET_NAME_Validate(r);
                }
                private static string _DATASET_NAME_GetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d)
                {
                    return d.ImplementationEntity.DATASET_NAME;
                }
                private static void _DATASET_NAME_SetImplementationValue(global::LightSwitchApplication.Dataset.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DATASET_NAME = v;
                }
                private static void _DATASET_NAME_OnValueChanged(global::LightSwitchApplication.Dataset e)
                {
                    e.DATASET_NAME_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data _INFORMATION_AREA_NAME;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data _SUBJECT_AREA_GROUP_NAME;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data _SUBJECT_AREA_NAME;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dataset, global::LightSwitchApplication.Dataset.DetailsClass, string>.Data _DATASET_NAME;
            
        }
    
        #endregion
    }
    
    #endregion
}
