

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class InformationArea : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the InformationArea entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public InformationArea()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public InformationArea(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.InformationArea> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.InformationArea.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InformationArea_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InformationArea_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string INFORMATION_AREA_NAME
        {
            get
            {
                return global::LightSwitchApplication.InformationArea.DetailsClass.GetValue(this, global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME);
            }
            set
            {
                global::LightSwitchApplication.InformationArea.DetailsClass.SetValue(this, global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void INFORMATION_AREA_NAME_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void INFORMATION_AREA_NAME_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void INFORMATION_AREA_NAME_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Cnt
        {
            get
            {
                return global::LightSwitchApplication.InformationArea.DetailsClass.GetValue(this, global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties.Cnt);
            }
            set
            {
                global::LightSwitchApplication.InformationArea.DetailsClass.SetValue(this, global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties.Cnt, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cnt_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cnt_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Cnt_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.InformationArea,
                global::LightSwitchApplication.InformationArea.DetailsClass,
                global::LightSwitchApplication.InformationArea.DetailsClass.IImplementation,
                global::LightSwitchApplication.InformationArea.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass>.Entry
                __InformationAreaEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass>.Entry(
                    global::LightSwitchApplication.InformationArea.DetailsClass.__InformationArea_CreateNew,
                    global::LightSwitchApplication.InformationArea.DetailsClass.__InformationArea_Created,
                    global::LightSwitchApplication.InformationArea.DetailsClass.__InformationArea_AllowSaveWithErrors);
            private static global::LightSwitchApplication.InformationArea __InformationArea_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.InformationArea> es)
            {
                return new global::LightSwitchApplication.InformationArea(es);
            }
            private static void __InformationArea_Created(global::LightSwitchApplication.InformationArea e)
            {
                e.InformationArea_Created();
            }
            private static bool __InformationArea_AllowSaveWithErrors(global::LightSwitchApplication.InformationArea e)
            {
                bool result = false;
                e.InformationArea_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.InformationArea.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, string> INFORMATION_AREA_NAME
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties.INFORMATION_AREA_NAME) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, global::System.Nullable<int>> Cnt
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties.Cnt) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string INFORMATION_AREA_NAME { get; set; }
                new global::System.Nullable<int> Cnt { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, string>.Entry
                    INFORMATION_AREA_NAME = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, string>.Entry(
                        "INFORMATION_AREA_NAME",
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_Stub,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_ComputeIsReadOnly,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_Validate,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_GetImplementationValue,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_SetImplementationValue,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._INFORMATION_AREA_NAME_OnValueChanged);
                private static void _INFORMATION_AREA_NAME_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.InformationArea.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, string>.Data> c, global::LightSwitchApplication.InformationArea.DetailsClass d, object sf)
                {
                    c(d, ref d._INFORMATION_AREA_NAME, sf);
                }
                private static bool _INFORMATION_AREA_NAME_ComputeIsReadOnly(global::LightSwitchApplication.InformationArea e)
                {
                    bool result = false;
                    e.INFORMATION_AREA_NAME_IsReadOnly(ref result);
                    return result;
                }
                private static void _INFORMATION_AREA_NAME_Validate(global::LightSwitchApplication.InformationArea e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.INFORMATION_AREA_NAME_Validate(r);
                }
                private static string _INFORMATION_AREA_NAME_GetImplementationValue(global::LightSwitchApplication.InformationArea.DetailsClass d)
                {
                    return d.ImplementationEntity.INFORMATION_AREA_NAME;
                }
                private static void _INFORMATION_AREA_NAME_SetImplementationValue(global::LightSwitchApplication.InformationArea.DetailsClass d, string v)
                {
                    d.ImplementationEntity.INFORMATION_AREA_NAME = v;
                }
                private static void _INFORMATION_AREA_NAME_OnValueChanged(global::LightSwitchApplication.InformationArea e)
                {
                    e.INFORMATION_AREA_NAME_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, global::System.Nullable<int>>.Entry
                    Cnt = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Cnt",
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._Cnt_Stub,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._Cnt_ComputeIsReadOnly,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._Cnt_Validate,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._Cnt_GetImplementationValue,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._Cnt_SetImplementationValue,
                        global::LightSwitchApplication.InformationArea.DetailsClass.PropertySetProperties._Cnt_OnValueChanged);
                private static void _Cnt_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.InformationArea.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.InformationArea.DetailsClass d, object sf)
                {
                    c(d, ref d._Cnt, sf);
                }
                private static bool _Cnt_ComputeIsReadOnly(global::LightSwitchApplication.InformationArea e)
                {
                    bool result = false;
                    e.Cnt_IsReadOnly(ref result);
                    return result;
                }
                private static void _Cnt_Validate(global::LightSwitchApplication.InformationArea e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Cnt_Validate(r);
                }
                private static global::System.Nullable<int> _Cnt_GetImplementationValue(global::LightSwitchApplication.InformationArea.DetailsClass d)
                {
                    return d.ImplementationEntity.Cnt;
                }
                private static void _Cnt_SetImplementationValue(global::LightSwitchApplication.InformationArea.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Cnt = v;
                }
                private static void _Cnt_OnValueChanged(global::LightSwitchApplication.InformationArea e)
                {
                    e.Cnt_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, string>.Data _INFORMATION_AREA_NAME;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.InformationArea, global::LightSwitchApplication.InformationArea.DetailsClass, global::System.Nullable<int>>.Data _Cnt;
            
        }
    
        #endregion
    }
    
    #endregion
}
