

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class EmployeeProject : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EmployeeProject entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmployeeProject()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmployeeProject(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmployeeProject> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EmployeeProject.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeProject_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeProject_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EmpID
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.EmpID);
            }
            set
            {
                global::LightSwitchApplication.EmployeeProject.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.EmpID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmpID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProjectID
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectID);
            }
            set
            {
                global::LightSwitchApplication.EmployeeProject.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TaskID
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.TaskID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TaskID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TaskID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TaskID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SubProject
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.SubProject);
            }
            set
            {
                global::LightSwitchApplication.EmployeeProject.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.SubProject, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubProject_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubProject_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubProject_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MonthID
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.MonthID);
            }
            set
            {
                global::LightSwitchApplication.EmployeeProject.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.MonthID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MonthID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> c_Date
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.c_Date);
            }
            set
            {
                global::LightSwitchApplication.EmployeeProject.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.c_Date, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Hours
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.Hours);
            }
            set
            {
                global::LightSwitchApplication.EmployeeProject.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.Hours, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hours_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hours_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hours_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ProjectTable ProjectTable
        {
            get
            {
                return global::LightSwitchApplication.EmployeeProject.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectTable);
            }
            set
            {
                global::LightSwitchApplication.EmployeeProject.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectTable, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectTable_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectTable_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectTable_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EmployeeProject,
                global::LightSwitchApplication.EmployeeProject.DetailsClass,
                global::LightSwitchApplication.EmployeeProject.DetailsClass.IImplementation,
                global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.EmpID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass>.Entry
                __EmployeeProjectEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass>.Entry(
                    global::LightSwitchApplication.EmployeeProject.DetailsClass.__EmployeeProject_CreateNew,
                    global::LightSwitchApplication.EmployeeProject.DetailsClass.__EmployeeProject_Created,
                    global::LightSwitchApplication.EmployeeProject.DetailsClass.__EmployeeProject_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EmployeeProject __EmployeeProject_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmployeeProject> es)
            {
                return new global::LightSwitchApplication.EmployeeProject(es);
            }
            private static void __EmployeeProject_Created(global::LightSwitchApplication.EmployeeProject e)
            {
                e.EmployeeProject_Created();
            }
            private static bool __EmployeeProject_AllowSaveWithErrors(global::LightSwitchApplication.EmployeeProject e)
            {
                bool result = false;
                e.EmployeeProject_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int> EmpID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.EmpID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int> ProjectID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int> TaskID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.TaskID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, string> SubProject
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.SubProject) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int> MonthID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.MonthID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::System.Nullable<global::System.DateTime>> c_Date
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.c_Date) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, decimal> Hours
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.Hours) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::LightSwitchApplication.ProjectTable> ProjectTable
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectTable) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::LightSwitchApplication.ProjectTable>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int EmpID { get; set; }
                new int ProjectID { get; set; }
                new int TaskID { get; }
                new string SubProject { get; set; }
                new int MonthID { get; set; }
                new global::System.Nullable<global::System.DateTime> c_Date { get; set; }
                new decimal Hours { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ProjectTable { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry
                    EmpID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry(
                        "EmpID",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._EmpID_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._EmpID_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._EmpID_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._EmpID_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._EmpID_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._EmpID_OnValueChanged);
                private static void _EmpID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._EmpID, sf);
                }
                private static bool _EmpID_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.EmpID_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmpID_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmpID_Validate(r);
                }
                private static int _EmpID_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.EmpID;
                }
                private static void _EmpID_SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d, int v)
                {
                    d.ImplementationEntity.EmpID = v;
                }
                private static void _EmpID_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.EmpID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry
                    ProjectID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry(
                        "ProjectID",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectID_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectID_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectID_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectID_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectID_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectID_OnValueChanged);
                private static void _ProjectID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectID, sf);
                }
                private static bool _ProjectID_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.ProjectID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectID_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectID_Validate(r);
                }
                private static int _ProjectID_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectID;
                }
                private static void _ProjectID_SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ProjectID = v;
                }
                private static void _ProjectID_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.ProjectID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry
                    TaskID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry(
                        "TaskID",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._TaskID_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._TaskID_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._TaskID_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._TaskID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._TaskID_OnValueChanged);
                private static void _TaskID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._TaskID, sf);
                }
                private static bool _TaskID_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.TaskID_IsReadOnly(ref result);
                    return result;
                }
                private static void _TaskID_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TaskID_Validate(r);
                }
                private static int _TaskID_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.TaskID;
                }
                private static void _TaskID_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.TaskID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, string>.Entry
                    SubProject = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, string>.Entry(
                        "SubProject",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._SubProject_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._SubProject_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._SubProject_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._SubProject_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._SubProject_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._SubProject_OnValueChanged);
                private static void _SubProject_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._SubProject, sf);
                }
                private static bool _SubProject_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.SubProject_IsReadOnly(ref result);
                    return result;
                }
                private static void _SubProject_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SubProject_Validate(r);
                }
                private static string _SubProject_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.SubProject;
                }
                private static void _SubProject_SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SubProject = v;
                }
                private static void _SubProject_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.SubProject_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry
                    MonthID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Entry(
                        "MonthID",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._MonthID_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._MonthID_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._MonthID_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._MonthID_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._MonthID_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._MonthID_OnValueChanged);
                private static void _MonthID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._MonthID, sf);
                }
                private static bool _MonthID_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.MonthID_IsReadOnly(ref result);
                    return result;
                }
                private static void _MonthID_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MonthID_Validate(r);
                }
                private static int _MonthID_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.MonthID;
                }
                private static void _MonthID_SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d, int v)
                {
                    d.ImplementationEntity.MonthID = v;
                }
                private static void _MonthID_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.MonthID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    c_Date = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "c_Date",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._c_Date_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._c_Date_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._c_Date_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._c_Date_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._c_Date_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._c_Date_OnValueChanged);
                private static void _c_Date_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Date, sf);
                }
                private static bool _c_Date_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.c_Date_IsReadOnly(ref result);
                    return result;
                }
                private static void _c_Date_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.c_Date_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _c_Date_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.c_Date;
                }
                private static void _c_Date_SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.c_Date = global::LightSwitchApplication.EmployeeProject.DetailsClass.TruncateDate(v);
                }
                private static void _c_Date_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.c_Date_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, decimal>.Entry
                    Hours = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, decimal>.Entry(
                        "Hours",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._Hours_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._Hours_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._Hours_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._Hours_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._Hours_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._Hours_OnValueChanged);
                private static void _Hours_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._Hours, sf);
                }
                private static bool _Hours_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.Hours_IsReadOnly(ref result);
                    return result;
                }
                private static void _Hours_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Hours_Validate(r);
                }
                private static decimal _Hours_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.Hours;
                }
                private static void _Hours_SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Hours = v;
                }
                private static void _Hours_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.Hours_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::LightSwitchApplication.ProjectTable>.Entry
                    ProjectTable = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::LightSwitchApplication.ProjectTable>.Entry(
                        "ProjectTable",
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_Stub,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_Validate,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_GetCoreImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_Refresh,
                        global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties._ProjectTable_OnValueChanged);
                private static void _ProjectTable_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeProject.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::LightSwitchApplication.ProjectTable>.Data> c, global::LightSwitchApplication.EmployeeProject.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectTable, sf);
                }
                private static bool _ProjectTable_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeProject e)
                {
                    bool result = false;
                    e.ProjectTable_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectTable_Validate(global::LightSwitchApplication.EmployeeProject e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectTable_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ProjectTable_GetCoreImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectTable;
                }
                private static global::LightSwitchApplication.ProjectTable _ProjectTable_GetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ProjectTable, global::LightSwitchApplication.ProjectTable.DetailsClass>(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectTable, ref d._ProjectTable);
                }
                private static void _ProjectTable_SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass d, global::LightSwitchApplication.ProjectTable v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectTable, ref d._ProjectTable, (i, ev) => i.ProjectTable = ev, v);
                }
                private static void _ProjectTable_Refresh(global::LightSwitchApplication.EmployeeProject.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EmployeeProject.DetailsClass.PropertySetProperties.ProjectTable, ref d._ProjectTable);
                }
                private static void _ProjectTable_OnValueChanged(global::LightSwitchApplication.EmployeeProject e)
                {
                    e.ProjectTable_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data _EmpID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data _ProjectID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data _TaskID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, string>.Data _SubProject;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, int>.Data _MonthID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _c_Date;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, decimal>.Data _Hours;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeProject, global::LightSwitchApplication.EmployeeProject.DetailsClass, global::LightSwitchApplication.ProjectTable>.Data _ProjectTable;
            
        }
    
        #endregion
    }
    
    #endregion
}
